version: "3.8"

services:
  react-native-app:
    build: .
    container_name: swiftcart-react-native-container
    ports:
      - "8081:8081"
    volumes:
      - ./SwiftCart-app:/app
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development

  mongodb:
    image: mongo:6
    container_name: swiftcart-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: swiftcart

volumes:
  mongodb_data:




