services:
  frontend:
    build:
      context: ./frontend  # Directory with frontend Dockerfile
    container_name: swiftcart-frontend
    ports:
      - "8081:8081"  # Expose Metro bundler port
    networks:
      - app-network
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    volumes:
      - ./frontend:/app  # Sync local changes
      - /app/node_modules

  backend:
    build:
      context: ./backend  # Directory with backend Dockerfile
    container_name: swiftcart-backend
    ports:
      - "3000:3000"  # Expose backend API port
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/swiftcartdb
    volumes:
      - ./backend:/app
    command: tail -f /dev/null

  mongodb:
    image: mongo:6
    container_name: swiftcart-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
